### PR TITLE
Trajectory visualizer

### PR DESCRIPTION
**Pull request by yakutovicha**

### CODE REVIEW

**Comment by yakutovicha** [comment]
To merge after #47. @csadorf please review that one as well.

**Comment by csadorf** [comment]
@yakutovicha It properly makes sense for me to hold of reviewing this PR until #47 is merged, would you agree?

**Comment by yakutovicha** [comment]
> @yakutovicha It properly makes sense for me to hold of reviewing this PR until #47 is merged, would you agree?

sure

**Comment by yakutovicha** [comment]
closing in favour of #51

**Pull request closed without merging**
