### PR TITLE
Bump version v2.2.0 -> v2.2.1

### PR DESCRIPTION
**Pull request by danielhollas**
@superstar54 I am assuming you want to make a new AWB release to include #597?
Is there something else that needs fixing?

### CODE REVIEW

**Comment by superstar54** [comment]
Thanks for reaching out, @danielhollas. @AndresOrtegaGuerrero and I recently discussed the possibility of releasing a new version of AWB, especially considering the inclusion of #597. While we see the value in a new release, AWB 2.2.0 was just launched, and we didn't want to impose by requesting another so soon. We truly appreciate your initiative to consider another release and are grateful for your support.

**Review by superstar54 — APPROVED** [review]

**Comment by superstar54** [comment]
> Is there something else that needs fixing?
Nothing else from my side. @AndresOrtegaGuerrero , do you have anything in mind?

**Comment by AndresOrtegaGuerrero** [comment]
> > Is there something else that needs fixing?
> 
> Nothing else from my side. @AndresOrtegaGuerrero , do you have anything in mind?

No, thank you @danielhollas !

**Comment by superstar54** [comment]
Hi @danielhollas , it seems that the AWB 2.2.1 has not been officially released.

**Comment by danielhollas** [comment]
@superstar54 thank you for the reminder, it is released now. https://pypi.org/project/aiidalab-widgets-base/

> While we see the value in a new release, AWB 2.2.0 was just launched, and we didn't want to impose by requesting another so soon.

No problem at all, this is what what patch releases are for, and this bugfix seemed important.

**Pull request merged**
