### PR TITLE
Resolve new flake8-bugbear error B028

### PR DESCRIPTION
**Pull request by yakutovicha**

### CODE REVIEW

**Comment by danielhollas** [comment]
@yakutovicha why wasn't this called earlier? I thought we pin the flake8 version so this shouldn't happen just by itself?

**Comment by yakutovicha** [comment]
> @yakutovicha why wasn't this caught earlier? I thought we pin the flake8 version so this shouldn't happen just by itself?

It's the new version of the flake8 plugin `flake8-bugbear`. We do not fix that one. Shall we?

**Comment by danielhollas** [comment]
> It's the new version of the flake8 plugin flake8-bugbear. We do not fix that one. Shall we?

Yeah, if possible we should perhaps fix the plugin versions to avoid this in the future.

**Review by danielhollas — DISMISSED** [review]

**Comment by yakutovicha** [comment]
> Feel free to merge this and pin the plugin versions later so we don't get distracted.

already done...

> btw: For my app I was considering using ruff, as a replacement for both flake8 and its plugins and isort.

if you think it is a better alternative, please make an issue. I am not sure what are the advantages, but happy to learn more about them.

**Comment by unkcpz** [comment]
Thanks @yakutovicha. This is what I mentioned gonna separate from https://github.com/aiidalab/aiidalab-widgets-base/pull/433#issuecomment-1440446993

**Comment by yakutovicha** [comment]
> Thanks @yakutovicha. This is what I mentioned gonna separate from [#433 (comment)](https://github.com/aiidalab/aiidalab-widgets-base/pull/433#issuecomment-1440446993)

Oh, sorry. I didn't know you've done that already.

**Comment by unkcpz** [comment]
Nonono, I need feel sorry that didn't manage to separate it. Thanks for doing this! 😉

**Pull request merged**
