### PR TITLE
Add timeout to cod query test to avoid test hang

### PR DESCRIPTION
**Pull request by unkcpz**
Temporary solution to timeout the cod query widget test.

### CODE REVIEW

**Comment by danielhollas** [comment]
Hmm, I would think that the timeout needs to be placed after the widget is initialized inside the test?

**Comment by unkcpz** [comment]
I want to timeout the test itself to not block the other tests, although it will failed in timeout which is expected for this case, after the cod is back, the test will pass.

**Comment by danielhollas** [comment]
I don't understand. Why is it expected that the test should timeout? We ideally want to fix the test itself no? Surely when the test times out it should fail the test suite, even if all other tests pass.

**Comment by unkcpz** [comment]
> Why is it expected that the test should timeout?

I don't think we can "fix" it, the problem is for the cod server side. Once the server is working, the test will pass. So if we find only this test failed and the cod server is not accessible, we can still continue with merging the PRs.

**Comment by danielhollas** [comment]
>  the problem is for the cod server side. Once the server is working,

Okay, could you please open an issue and explain in detail what the problem is? In the meantime, I would suggest to simply skip the test (`@pytest.mark.skip` I think). That's a much easier and more robust solution than the timeout.

**Comment by yakutovicha** [comment]
The test is passing now, btw.

**Comment by unkcpz** [comment]
@yakutovicha thanks!
I think it is not a bad idea to add the timeout, then we don't stuck the test in the future if the cod server not accessible again in the future (although quite rare I hope). If skip it, then it requires to change the test by PRs. If you think it not worth to do like this I'll close the PR.

**Comment by yakutovicha** [comment]
I think it is not a bad idea to add the timeout, then we don't stuck the test in the future if the cod server not accessible again in the future (although quite rare I hope).

So as far as I can see, adding the timeout doesn't solve the test problem itself, but just speeds up the test failure in case of trouble. Which is not a bad thing, in the end.

To resolve the issue we might monkey-patch the output of the request sent to the COD, but that is for another PR. Not sure if this is a good idea, though. Because if COD changes something, then the problem might go unnoticed.

**Comment by danielhollas** [comment]
Sure, let's try it, but the tests are currently failing??

**Comment by unkcpz** [comment]
I didn't retrigger the test after COD was alive. All passed now :)

**Review by danielhollas — APPROVED** [review]

**Pull request merged**
